#!/bin/sh
#
# This hook is invoked when a 'git checkout' (or 'git clone') is run, after having updated the worktree
# Start from the repository root and do the following:
# delete all .pyc and .pyo files

cd ./$(git rev-parse --show-cdup)

# Delete .pyc and .pyo files
find . -name "*.pyc" -delete
find . -name "*.pyo" -delete
# Delete all empty directories
# find . -type d -empty -delete
